### ISSUE TITLE
Buttons not sending service calls to HA

### ISSUE THREAD

**Issue by camokarzi** [GuySie/cyd-thermostat#1]
Hi
Great work with this Thermostat. I really like the work you put into it.

I am having an issue where pressing any buttons does not change the thermostat settings  

ESPhome reports the correct button pressed: 

eg:
[D][xpt2046:055]: Touchscreen Update [2296, 727], z = 1447
[12:44:06][D][binary_sensor:036]: 'Off button': Sending state ON
[12:44:06][D][main:299]: Turn off heating mode
[12:44:07][D][binary_sensor:036]: 'Off button': Sending state OFF

Thus no action occurs in HA

though setting the thermostat in HA does change the display settings

I tried modifying a tad also with no luck

# Off button to turn off heating mode
  - platform: touchscreen
    name: "Off button"
    id: offbutton
    x_min: 20
    x_max: 80
    y_min: 80
    y_max: 120
    on_press:
      then:
        - component.update: cyd
        - logger.log: "Turn off heating mode"
        - homeassistant.service:
             service: climate.turn_off
             data:
               entity_id: climate.abbys_bedroom
    on_release:
      then:
        - component.update: cyd

**Comment by GuySie** [comment]
Hmm, weird! Do the climate.turn_off and climate.turn_on service calls work with your thermostat if you call them manually through the developer tools?

**Comment by camokarzi** [comment]
Thanks GuySie  I did more investigation, your code is good and works. I needed to allow ESPhome to make direct service calls which is now not default.  After this the code worked like a charm. 

Thanks for your qik reply.

**Comment by GuySie** [comment]
Great to hear you got it fixed. I wasn't aware this default behavior had changed. Thanks for pointing it out, I've updated the readme!
